return {
    binding = require("core.binding"),
    client = require("core.client"),
    selection = require("core.selection"),
    layout = require("core.layout"),
    mouse = require("core.mouse"),
    notification = require("core.notification"),
    path = require("core.path"),
    rule = require("core.rule"),
    screen = require("core.screen"),
    style = require("core.style"),
    system = require("core.system"),
    tag = require("core.tag"),
    widget = require("core.widget"),
    workspace = require("core.workspace"),
}
