return {
    capsule = require("ext.capsule"),
    taglist = require("ext.taglist"),

    -- arcchart = require("wibox.container.arcchart"),
    -- background = require("wibox.container.background"),
    -- constraint = require("wibox.container.constraint"),
    -- margin = require("wibox.container.margin"),
    -- mirror = require("wibox.container.mirror"),
    -- place = require("wibox.container.place"),
    -- radialprogressbar = require("wibox.container.radialprogressbar"),
    -- rotate = require("wibox.container.rotate"),
    -- scroll = require("wibox.container.scroll"),
    -- tile = require("wibox.container.tile"),

    -- align = require("wibox.layout.align"),
    -- fixed = require("wibox.layout.fixed"),
    -- flex = require("wibox.layout.flex"),
    -- grid = require("wibox.layout.grid"),
    -- manual = require("wibox.layout.manual"),
    -- ratio = require("wibox.layout.ratio"),
    -- stack = require("wibox.layout.stack"),

    -- calendar = require("wibox.widget.calendar"),
    -- checkbox = require("wibox.widget.checkbox"),
    -- graph = require("wibox.widget.graph"),
    -- imagebox = require("wibox.widget.imagebox"),
    -- piechart = require("wibox.widget.piechart"),
    -- progressbar = require("wibox.widget.progressbar"),
    -- separator = require("wibox.widget.separator"),
    -- slider = require("wibox.widget.slider"),
    -- systray = require("wibox.widget.systray"),
    -- textbox = require("wibox.widget.textbox"),
    -- textclock = require("wibox.widget.textclock"),
}
