---@meta _

---@alias thickness { top: number, right: number, bottom: number, left: number }
---@alias geometry { x: number, y: number, width: number, height: number }
---@alias point { x: number, y: number }
---@alias size { width: number, height: number }
---@alias sign -1|0|1
---@alias direction "up"|"right"|"bottom"|"left"
---@alias orientation "vertical"|"horizontal"
---@alias halign "left"|"center"|"right"
---@alias valign "top"|"center"|"bottom"
---@alias text_ellipsize 
---| "start"
---| "middle"
---|>"end"
---| "none"
---@alias text_wrap 
---| "word"
---| "char"
---|>"word_char"
---@alias shape fun(cr: cairo_context, width: number, height: number)

---@alias font string
---@alias color string
